/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MapBoxMap {
        /**
          * To use Mapbox GL JS, you need to have a Mapbox access token. https://docs.mapbox.com/mapbox-gl-js/guides/install/#:~:text=have%20a%20Mapbox-,access%20token,-.%20This%20access%20token
          * @type {string}
         */
        "accessToken": string | undefined;
        /**
          * Represents the height of a map. Supported all CSS values. Default value: '100%'
          * @type {string}
         */
        "height": string;
        /**
          * Represents the latitude coordinate of a geographical location.
          * @type {number}
         */
        "lat": number;
        /**
          * Represents the longitude coordinate of a geographical location.
          * @type {number}
         */
        "lng": number;
        /**
          * Url to your Map Box style https://docs.mapbox.com/help/dive-deeper/map-design/
          * @type {string}
         */
        "mapStyle": string | undefined;
        /**
          * Set height in pixels for marker
          * @type {string}
         */
        "markerHeight": string;
        /**
          * Represents the URL of the marker icon to be used in a map. If no url there will be used default icon.  Sometimes the default icon can be restricted like in VitVe https://vite.dev/config/server-options.html#server-fs-allow
          * @type {string}
         */
        "markerUrl": string | undefined;
        /**
          * Set width in pixels for marker
          * @type {string}
         */
        "markerWidth": string;
        /**
          * Represents the width of a map. Supported all CSS values. Default value: '100%'
          * @type {string}
         */
        "width": string;
        /**
          * Initial zoom level min 0, max 15
          * @type {number}
         */
        "zoom": number;
    }
}
declare global {
    interface HTMLMapBoxMapElement extends Components.MapBoxMap, HTMLStencilElement {
    }
    var HTMLMapBoxMapElement: {
        prototype: HTMLMapBoxMapElement;
        new (): HTMLMapBoxMapElement;
    };
    interface HTMLElementTagNameMap {
        "map-box-map": HTMLMapBoxMapElement;
    }
}
declare namespace LocalJSX {
    interface MapBoxMap {
        /**
          * To use Mapbox GL JS, you need to have a Mapbox access token. https://docs.mapbox.com/mapbox-gl-js/guides/install/#:~:text=have%20a%20Mapbox-,access%20token,-.%20This%20access%20token
          * @type {string}
         */
        "accessToken"?: string | undefined;
        /**
          * Represents the height of a map. Supported all CSS values. Default value: '100%'
          * @type {string}
         */
        "height"?: string;
        /**
          * Represents the latitude coordinate of a geographical location.
          * @type {number}
         */
        "lat"?: number;
        /**
          * Represents the longitude coordinate of a geographical location.
          * @type {number}
         */
        "lng"?: number;
        /**
          * Url to your Map Box style https://docs.mapbox.com/help/dive-deeper/map-design/
          * @type {string}
         */
        "mapStyle"?: string | undefined;
        /**
          * Set height in pixels for marker
          * @type {string}
         */
        "markerHeight"?: string;
        /**
          * Represents the URL of the marker icon to be used in a map. If no url there will be used default icon.  Sometimes the default icon can be restricted like in VitVe https://vite.dev/config/server-options.html#server-fs-allow
          * @type {string}
         */
        "markerUrl"?: string | undefined;
        /**
          * Set width in pixels for marker
          * @type {string}
         */
        "markerWidth"?: string;
        /**
          * Represents the width of a map. Supported all CSS values. Default value: '100%'
          * @type {string}
         */
        "width"?: string;
        /**
          * Initial zoom level min 0, max 15
          * @type {number}
         */
        "zoom"?: number;
    }
    interface IntrinsicElements {
        "map-box-map": MapBoxMap;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "map-box-map": LocalJSX.MapBoxMap & JSXBase.HTMLAttributes<HTMLMapBoxMapElement>;
        }
    }
}
